/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.MainProduct;
import javax.swing.JOptionPane;
/**
 *
 * @author 16177
 */
public class AddInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInfoJPanel
     */
     MainProduct product;
    public AddInfoJPanel(MainProduct product, String string) {
        initComponents();
        this.product = product;
         if(string=="create")
        {
            
        }
        else
        {
            SaveJButton.setVisible(false);
            StreetAddJText.setEnabled(false);
            CityJText.setEnabled(false);
            StateJText.setEnabled(false);
            ZipCodeJText.setEnabled(false);
             display();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StreetAddJText = new javax.swing.JTextField();
        CityJText = new javax.swing.JTextField();
        AddInfoJLabel = new javax.swing.JLabel();
        StateJText = new javax.swing.JTextField();
        StreetAddJLable = new javax.swing.JLabel();
        ZipCodeJText = new javax.swing.JTextField();
        CityJLable = new javax.swing.JLabel();
        StateJLable = new javax.swing.JLabel();
        ZipCodeJLable = new javax.swing.JLabel();
        SaveJButton = new javax.swing.JButton();

        AddInfoJLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        AddInfoJLabel.setForeground(new java.awt.Color(153, 0, 0));
        AddInfoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddInfoJLabel.setText("Address Information");
        AddInfoJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        StreetAddJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        StreetAddJLable.setText("Street Address:");

        ZipCodeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeJTextActionPerformed(evt);
            }
        });

        CityJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        CityJLable.setText("City:");

        StateJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        StateJLable.setText("State:");

        ZipCodeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        ZipCodeJLable.setText("Zip Code:");

        SaveJButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        SaveJButton.setForeground(new java.awt.Color(102, 102, 0));
        SaveJButton.setText("SAVE");
        SaveJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SaveJButton.setBorderPainted(false);
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StateJLable)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CityJLable, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(StreetAddJLable))
                    .addComponent(ZipCodeJLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CityJText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StreetAddJText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StateJText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddInfoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(AddInfoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetAddJLable)
                    .addComponent(StreetAddJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityJLable)
                    .addComponent(CityJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StateJLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZipCodeJLable)
                    .addComponent(ZipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
        // TODO add your handling code here:
        product.setStreetAdrs(StreetAddJText.getText());
       product.setCity(CityJText.getText());
       product.setState(StateJText.getText());
       product.setZipcode(ZipCodeJText.getText());
        JOptionPane.showMessageDialog(this, "Saved Successfully");
    }//GEN-LAST:event_SaveJButtonActionPerformed

    private void ZipCodeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeJTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddInfoJLabel;
    private javax.swing.JLabel CityJLable;
    private javax.swing.JTextField CityJText;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JLabel StateJLable;
    private javax.swing.JTextField StateJText;
    private javax.swing.JLabel StreetAddJLable;
    private javax.swing.JTextField StreetAddJText;
    private javax.swing.JLabel ZipCodeJLable;
    private javax.swing.JTextField ZipCodeJText;
    // End of variables declaration//GEN-END:variables

    private void display() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        StreetAddJText.setText(product.getStreetAdrs());
        CityJText.setText(product.getCity());
        StateJText.setText(product.getState());
        ZipCodeJText.setText(product.getZipcode());
    }
}
