/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.MainProduct;
import UI.MainJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 16177
 */
public class DemoInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemoInfoJPanel
     */
    MainProduct product;
    public DemoInfoJPanel(MainProduct product, String string) {
        initComponents();
        this.product= product;
        if(string=="create")
        {
            
        }
        else
        {
            SaveJButton.setVisible(false);
            FirstNameJText.setEnabled(false);
            LastNameJText.setEnabled(false);
            PhoneNumberJText.setEnabled(false);
            DOBJText.setEnabled(false);
            AgeJText.setEnabled(false);
            HeightJText.setEnabled(false);
               WeightJText.setEnabled(false);
            SSNJText.setEnabled(false);
             display();
              
        }
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleJLabel = new javax.swing.JLabel();
        FirstNameJLable = new javax.swing.JLabel();
        LastNameJLable = new javax.swing.JLabel();
        PhoneNumberJLable = new javax.swing.JLabel();
        DOBJLable = new javax.swing.JLabel();
        AgeJLable = new javax.swing.JLabel();
        HeightJLable = new javax.swing.JLabel();
        WeightJLable = new javax.swing.JLabel();
        SSNJLable = new javax.swing.JLabel();
        FirstNameJText = new javax.swing.JTextField();
        LastNameJText = new javax.swing.JTextField();
        PhoneNumberJText = new javax.swing.JTextField();
        DOBJText = new javax.swing.JTextField();
        AgeJText = new javax.swing.JTextField();
        HeightJText = new javax.swing.JTextField();
        WeightJText = new javax.swing.JTextField();
        SSNJText = new javax.swing.JTextField();
        SaveJButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        setPreferredSize(new java.awt.Dimension(544, 436));

        TitleJLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        TitleJLabel.setForeground(new java.awt.Color(153, 0, 0));
        TitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleJLabel.setText("Demographic Information");
        TitleJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        FirstNameJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        FirstNameJLable.setText("First Name:");

        LastNameJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        LastNameJLable.setText("Last Name:");

        PhoneNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        PhoneNumberJLable.setText("Phone Number:");

        DOBJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOBJLable.setText("Date of Birth:");

        AgeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AgeJLable.setText("Age:");

        HeightJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        HeightJLable.setText("Height:");

        WeightJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        WeightJLable.setText("Weight:");

        SSNJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        SSNJLable.setText("Social Security Number:");

        FirstNameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameJTextActionPerformed(evt);
            }
        });

        HeightJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightJTextActionPerformed(evt);
            }
        });

        SaveJButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        SaveJButton.setForeground(new java.awt.Color(102, 102, 0));
        SaveJButton.setText("SAVE");
        SaveJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SaveJButton.setBorderPainted(false);
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameJLable)
                            .addComponent(FirstNameJLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOBJLable)
                            .addComponent(PhoneNumberJLable)
                            .addComponent(AgeJLable)
                            .addComponent(HeightJLable)
                            .addComponent(WeightJLable)
                            .addComponent(SSNJLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SSNJText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstNameJLable)
                    .addComponent(FirstNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameJLable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumberJLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBJLable)
                    .addComponent(DOBJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeJLable)
                    .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightJLable)
                    .addComponent(HeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeightJLable)
                    .addComponent(WeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNJLable)
                    .addComponent(SSNJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HeightJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightJTextActionPerformed

    
    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
        // TODO add your handling code here:
        product.setFirstname(FirstNameJText.getText());
        product.setLastname(LastNameJText.getText());
        product.setPhonenumber(PhoneNumberJText.getText());
        product.setDob(DOBJText.getText());
        product.setAge(AgeJText.getText());
        product.setHeight(HeightJText.getText());
        product.setWeight(WeightJText.getText());
        product.setSsn(SSNJText.getText());
       
        JOptionPane.showMessageDialog(this, "Saved Successfully");      
    }//GEN-LAST:event_SaveJButtonActionPerformed

    private void FirstNameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameJTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLable;
    private javax.swing.JTextField AgeJText;
    private javax.swing.JLabel DOBJLable;
    private javax.swing.JTextField DOBJText;
    private javax.swing.JLabel FirstNameJLable;
    private javax.swing.JTextField FirstNameJText;
    private javax.swing.JLabel HeightJLable;
    private javax.swing.JTextField HeightJText;
    private javax.swing.JLabel LastNameJLable;
    private javax.swing.JTextField LastNameJText;
    private javax.swing.JLabel PhoneNumberJLable;
    private javax.swing.JTextField PhoneNumberJText;
    private javax.swing.JLabel SSNJLable;
    private javax.swing.JTextField SSNJText;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.JLabel WeightJLable;
    private javax.swing.JTextField WeightJText;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables

    private void display() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        FirstNameJText.setText(product.getFirstname());
        LastNameJText.setText(product.getLastname());
        PhoneNumberJText.setText(product.getPhonenumber());
        DOBJText.setText(product.getDob());
        AgeJText.setText(product.getAge());
        HeightJText.setText(product.getHeight());
        WeightJText.setText(product.getWeight());
        SSNJText.setText(product.getSsn());
    
    }
}
