/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.MainProduct;

/**
 *
 * @author 16177
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    MainProduct product;
    public MainJFrame() {
        initComponents();
        product = new MainProduct();
       setExtendedState(MainJFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleJLabel = new javax.swing.JLabel();
        SplitPane = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        DemoInfoCreateJButton = new javax.swing.JButton();
        CreateSavAccInfoJButton = new javax.swing.JButton();
        CheckAccInfocreateJButton = new javax.swing.JButton();
        DriLicInfoCreateJButton = new javax.swing.JButton();
        MediInnfoCreateJButton = new javax.swing.JButton();
        PrintJButton = new javax.swing.JButton();
        AdrsJlLabel = new javax.swing.JLabel();
        AddInfoViewJButton = new javax.swing.JButton();
        DemoInfoViewJButton = new javax.swing.JButton();
        DemoInfoJlLabel = new javax.swing.JLabel();
        AddInfoCreateJButton = new javax.swing.JButton();
        SavingJlLabel = new javax.swing.JLabel();
        viewSavAccInfoJButton = new javax.swing.JButton();
        CheckinJlLabel = new javax.swing.JLabel();
        CheckAccInfocreateviewJButton = new javax.swing.JButton();
        LicenseJlLabel = new javax.swing.JLabel();
        DriLicInfoViewJButton = new javax.swing.JButton();
        LicenseJlLabel1 = new javax.swing.JLabel();
        MediiInfoViewJButton = new javax.swing.JButton();
        WorkJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleJLabel.setBackground(new java.awt.Color(51, 0, 153));
        TitleJLabel.setFont(new java.awt.Font("STZhongsong", 1, 18)); // NOI18N
        TitleJLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleJLabel.setText("PERSONAL INFORMATION REPORT");
        TitleJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        TitleJLabel.setOpaque(true);

        SplitPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102), 2));
        SplitPane.setDividerLocation(300);
        SplitPane.setForeground(new java.awt.Color(51, 0, 51));

        ControlJPanel.setBackground(new java.awt.Color(51, 0, 51));
        ControlJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        DemoInfoCreateJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        DemoInfoCreateJButton.setText("Create");
        DemoInfoCreateJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        DemoInfoCreateJButton.setBorderPainted(false);
        DemoInfoCreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoInfoCreateJButtonActionPerformed(evt);
            }
        });

        CreateSavAccInfoJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        CreateSavAccInfoJButton.setText("Create");
        CreateSavAccInfoJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CreateSavAccInfoJButton.setBorderPainted(false);
        CreateSavAccInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateSavAccInfoJButtonActionPerformed(evt);
            }
        });

        CheckAccInfocreateJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        CheckAccInfocreateJButton.setText("Create");
        CheckAccInfocreateJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CheckAccInfocreateJButton.setBorderPainted(false);
        CheckAccInfocreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAccInfocreateJButtonActionPerformed(evt);
            }
        });

        DriLicInfoCreateJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        DriLicInfoCreateJButton.setText("Create");
        DriLicInfoCreateJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DriLicInfoCreateJButton.setBorderPainted(false);
        DriLicInfoCreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriLicInfoCreateJButtonActionPerformed(evt);
            }
        });

        MediInnfoCreateJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        MediInnfoCreateJButton.setText("Create");
        MediInnfoCreateJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MediInnfoCreateJButton.setBorderPainted(false);
        MediInnfoCreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediInnfoCreateJButtonActionPerformed(evt);
            }
        });

        PrintJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        PrintJButton.setText("Pirnt Report");
        PrintJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.red));
        PrintJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintJButtonActionPerformed(evt);
            }
        });

        AdrsJlLabel.setBackground(new java.awt.Color(0, 51, 204));
        AdrsJlLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        AdrsJlLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdrsJlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdrsJlLabel.setText("Address Information");
        AdrsJlLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        AddInfoViewJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        AddInfoViewJButton.setText("View");
        AddInfoViewJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AddInfoViewJButton.setBorderPainted(false);
        AddInfoViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInfoViewJButtonActionPerformed(evt);
            }
        });

        DemoInfoViewJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        DemoInfoViewJButton.setText("View");
        DemoInfoViewJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DemoInfoViewJButton.setBorderPainted(false);
        DemoInfoViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoInfoViewJButtonActionPerformed(evt);
            }
        });

        DemoInfoJlLabel.setBackground(new java.awt.Color(0, 51, 204));
        DemoInfoJlLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        DemoInfoJlLabel.setForeground(new java.awt.Color(255, 255, 255));
        DemoInfoJlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoInfoJlLabel.setText("Demographic Information");
        DemoInfoJlLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        AddInfoCreateJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        AddInfoCreateJButton.setText("Create");
        AddInfoCreateJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AddInfoCreateJButton.setBorderPainted(false);
        AddInfoCreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInfoCreateJButtonActionPerformed(evt);
            }
        });

        SavingJlLabel.setBackground(new java.awt.Color(0, 51, 204));
        SavingJlLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        SavingJlLabel.setForeground(new java.awt.Color(255, 255, 255));
        SavingJlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SavingJlLabel.setText("Saving Account Information");
        SavingJlLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        viewSavAccInfoJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        viewSavAccInfoJButton.setText("View");
        viewSavAccInfoJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        viewSavAccInfoJButton.setBorderPainted(false);
        viewSavAccInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSavAccInfoJButtonActionPerformed(evt);
            }
        });

        CheckinJlLabel.setBackground(new java.awt.Color(0, 51, 204));
        CheckinJlLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        CheckinJlLabel.setForeground(new java.awt.Color(255, 255, 255));
        CheckinJlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckinJlLabel.setText("Checking Account Information");
        CheckinJlLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        CheckAccInfocreateviewJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        CheckAccInfocreateviewJButton.setText("View");
        CheckAccInfocreateviewJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CheckAccInfocreateviewJButton.setBorderPainted(false);
        CheckAccInfocreateviewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAccInfocreateviewJButtonActionPerformed(evt);
            }
        });

        LicenseJlLabel.setBackground(new java.awt.Color(0, 51, 204));
        LicenseJlLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        LicenseJlLabel.setForeground(new java.awt.Color(255, 255, 255));
        LicenseJlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LicenseJlLabel.setText("Driver License Information");
        LicenseJlLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        DriLicInfoViewJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        DriLicInfoViewJButton.setText("View");
        DriLicInfoViewJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DriLicInfoViewJButton.setBorderPainted(false);
        DriLicInfoViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriLicInfoViewJButtonActionPerformed(evt);
            }
        });

        LicenseJlLabel1.setBackground(new java.awt.Color(0, 51, 204));
        LicenseJlLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        LicenseJlLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LicenseJlLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LicenseJlLabel1.setText("Medical Information");
        LicenseJlLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        MediiInfoViewJButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        MediiInfoViewJButton.setText("View");
        MediiInfoViewJButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MediiInfoViewJButton.setBorderPainted(false);
        MediiInfoViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediiInfoViewJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJPanelLayout = new javax.swing.GroupLayout(ControlJPanel);
        ControlJPanel.setLayout(ControlJPanelLayout);
        ControlJPanelLayout.setHorizontalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MediiInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ControlJPanelLayout.createSequentialGroup()
                                .addComponent(MediInnfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ControlJPanelLayout.createSequentialGroup()
                                    .addComponent(DriLicInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(DriLicInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LicenseJlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                                        .addComponent(CheckAccInfocreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CheckAccInfocreateviewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckinJlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                                        .addComponent(CreateSavAccInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewSavAccInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SavingJlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AdrsJlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(ControlJPanelLayout.createSequentialGroup()
                                        .addComponent(AddInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlJPanelLayout.createSequentialGroup()
                                        .addComponent(DemoInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DemoInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DemoInfoJlLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(LicenseJlLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrintJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJPanelLayout.setVerticalGroup(
            ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DemoInfoJlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DemoInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DemoInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdrsJlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SavingJlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSavAccInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateSavAccInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CheckinJlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckAccInfocreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckAccInfocreateviewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LicenseJlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriLicInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DriLicInfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LicenseJlLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MediiInfoViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MediInnfoCreateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(PrintJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ControlJPanel);

        WorkJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        javax.swing.GroupLayout WorkJPanelLayout = new javax.swing.GroupLayout(WorkJPanel);
        WorkJPanel.setLayout(WorkJPanelLayout);
        WorkJPanelLayout.setHorizontalGroup(
            WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        WorkJPanelLayout.setVerticalGroup(
            WorkJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(WorkJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SplitPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemoInfoCreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoInfoCreateJButtonActionPerformed
        // TODO add your handling code here:
        DemoInfoJPanel DemoInfo = new DemoInfoJPanel(product,"create");
        SplitPane.setRightComponent(DemoInfo);
                
    }//GEN-LAST:event_DemoInfoCreateJButtonActionPerformed

    private void CheckAccInfocreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAccInfocreateJButtonActionPerformed
        // TODO add your handling code here:
        CheckingAccInfoJPannel CheckingInfo = new CheckingAccInfoJPannel(product,"create");
        SplitPane.setRightComponent(CheckingInfo);
    }//GEN-LAST:event_CheckAccInfocreateJButtonActionPerformed

    private void AddInfoViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInfoViewJButtonActionPerformed
        // TODO add your handling code here:"
        AddInfoJPanel AddInfo = new AddInfoJPanel(product,"View");
        SplitPane.setRightComponent(AddInfo);
    }//GEN-LAST:event_AddInfoViewJButtonActionPerformed

    private void CreateSavAccInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateSavAccInfoJButtonActionPerformed
        // TODO add your handling code here:
        SavingAccInfoJPanel SavingInfo = new SavingAccInfoJPanel(product,"create");
        SplitPane.setRightComponent(SavingInfo);
    }//GEN-LAST:event_CreateSavAccInfoJButtonActionPerformed

    private void DriLicInfoCreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriLicInfoCreateJButtonActionPerformed
        // TODO add your handling code here:
        DriverInfoJPanel DriverInfo = new DriverInfoJPanel(product);
        SplitPane.setRightComponent(DriverInfo);
    }//GEN-LAST:event_DriLicInfoCreateJButtonActionPerformed

    private void MediInnfoCreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediInnfoCreateJButtonActionPerformed
        // TODO add your handling code here:
        MedicalInfoJPanel MedicalInfo = new MedicalInfoJPanel(product,"create");
        SplitPane.setRightComponent(MedicalInfo);
    }//GEN-LAST:event_MediInnfoCreateJButtonActionPerformed

    private void PrintJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintJButtonActionPerformed
        // TODO add your handling code here:
        PrintResultJPanel PrintResult = new PrintResultJPanel(product);
        SplitPane.setRightComponent(PrintResult);
    }//GEN-LAST:event_PrintJButtonActionPerformed

    private void DemoInfoViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoInfoViewJButtonActionPerformed
        // TODO add your handling code here:
         DemoInfoJPanel DemoInfo = new DemoInfoJPanel(product,"view");
        SplitPane.setRightComponent(DemoInfo);
    }//GEN-LAST:event_DemoInfoViewJButtonActionPerformed

    private void AddInfoCreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInfoCreateJButtonActionPerformed
        // TODO add your handling code here:
         AddInfoJPanel AddInfo = new AddInfoJPanel(product,"create");
        SplitPane.setRightComponent(AddInfo);
    }//GEN-LAST:event_AddInfoCreateJButtonActionPerformed

    private void viewSavAccInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSavAccInfoJButtonActionPerformed
        // TODO add your handling code here:
         SavingAccInfoJPanel SavingInfo = new SavingAccInfoJPanel(product,"view");
        SplitPane.setRightComponent(SavingInfo);
    }//GEN-LAST:event_viewSavAccInfoJButtonActionPerformed

    private void CheckAccInfocreateviewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAccInfocreateviewJButtonActionPerformed
        // TODO add your handling code here:
          CheckingAccInfoJPannel CheckingInfo = new CheckingAccInfoJPannel(product,"view");
        SplitPane.setRightComponent(CheckingInfo);
    }//GEN-LAST:event_CheckAccInfocreateviewJButtonActionPerformed

    private void DriLicInfoViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriLicInfoViewJButtonActionPerformed
        // TODO add your handling code here:
         ViewLicenseInfoJPanel DriverInfo = new ViewLicenseInfoJPanel(product);
        SplitPane.setRightComponent(DriverInfo);
    }//GEN-LAST:event_DriLicInfoViewJButtonActionPerformed

    private void MediiInfoViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediiInfoViewJButtonActionPerformed
        // TODO add your handling code here:
        MedicalInfoJPanel MedicalInfo = new MedicalInfoJPanel(product,"view");
        SplitPane.setRightComponent(MedicalInfo);
    }//GEN-LAST:event_MediiInfoViewJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInfoCreateJButton;
    private javax.swing.JButton AddInfoViewJButton;
    private javax.swing.JLabel AdrsJlLabel;
    private javax.swing.JButton CheckAccInfocreateJButton;
    private javax.swing.JButton CheckAccInfocreateviewJButton;
    private javax.swing.JLabel CheckinJlLabel;
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton CreateSavAccInfoJButton;
    private javax.swing.JButton DemoInfoCreateJButton;
    private javax.swing.JLabel DemoInfoJlLabel;
    private javax.swing.JButton DemoInfoViewJButton;
    private javax.swing.JButton DriLicInfoCreateJButton;
    private javax.swing.JButton DriLicInfoViewJButton;
    private javax.swing.JLabel LicenseJlLabel;
    private javax.swing.JLabel LicenseJlLabel1;
    private javax.swing.JButton MediInnfoCreateJButton;
    private javax.swing.JButton MediiInfoViewJButton;
    private javax.swing.JButton PrintJButton;
    private javax.swing.JLabel SavingJlLabel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.JPanel WorkJPanel;
    private javax.swing.JButton viewSavAccInfoJButton;
    // End of variables declaration//GEN-END:variables
}
