/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.MainProduct;
import javax.swing.JOptionPane;

/**
 *
 * @author 16177
 */
public class MedicalInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalInfoJPanel
     */
    MainProduct product;
    public MedicalInfoJPanel(MainProduct product,String string) {
        initComponents();
        this.product = product;
              if(string=="create")
        {
            
        }
        else
        {
            SaveJButton1.setVisible(false);
            MedicalRecNumberJText.setEnabled(false);
        Alergy1JText.setEnabled(false);
        Alergy2JText.setEnabled(false);
        Alergy3JText.setEnabled(false);
             display();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedicalRecNumberJText = new javax.swing.JTextField();
        Alergy1JText = new javax.swing.JTextField();
        TitleJLabel = new javax.swing.JLabel();
        Alergy2JText = new javax.swing.JTextField();
        MedicalRecNumberJLable = new javax.swing.JLabel();
        Alergy3JText = new javax.swing.JTextField();
        Allergy1JLable = new javax.swing.JLabel();
        Alergy2JLable = new javax.swing.JLabel();
        Alergy3JLable = new javax.swing.JLabel();
        SaveJButton1 = new javax.swing.JButton();

        TitleJLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        TitleJLabel.setForeground(new java.awt.Color(153, 0, 0));
        TitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleJLabel.setText("Medical Information");
        TitleJLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));

        MedicalRecNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MedicalRecNumberJLable.setText("Medical Record Number:");

        Allergy1JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Allergy1JLable.setText("Alergy 1:");

        Alergy2JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Alergy2JLable.setText("Alergy 2:");

        Alergy3JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Alergy3JLable.setText("Alergy 3:");

        SaveJButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        SaveJButton1.setForeground(new java.awt.Color(102, 102, 0));
        SaveJButton1.setText("SAVE");
        SaveJButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        SaveJButton1.setBorderPainted(false);
        SaveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 342, Short.MAX_VALUE)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Allergy1JLable)
                    .addComponent(MedicalRecNumberJLable)
                    .addComponent(Alergy2JLable)
                    .addComponent(Alergy3JLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Alergy2JText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(Alergy1JText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicalRecNumberJText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alergy3JText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalRecNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicalRecNumberJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Allergy1JLable)
                    .addComponent(Alergy1JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy2JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy2JLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy3JLable)
                    .addComponent(Alergy3JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButton1ActionPerformed
        // TODO add your handling code here:
        product.setMedrecno(MedicalRecNumberJText.getText());
        product.setA1(Alergy1JText.getText());
        product.setA2(Alergy2JText.getText());
        product.setA3(Alergy3JText.getText());
        
         JOptionPane.showMessageDialog(this, "Saved Successfully");
    }//GEN-LAST:event_SaveJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergy1JText;
    private javax.swing.JLabel Alergy2JLable;
    private javax.swing.JTextField Alergy2JText;
    private javax.swing.JLabel Alergy3JLable;
    private javax.swing.JTextField Alergy3JText;
    private javax.swing.JLabel Allergy1JLable;
    private javax.swing.JLabel MedicalRecNumberJLable;
    private javax.swing.JTextField MedicalRecNumberJText;
    private javax.swing.JButton SaveJButton1;
    private javax.swing.JLabel TitleJLabel;
    // End of variables declaration//GEN-END:variables

    private void display() {
        
        MedicalRecNumberJText.setText(product.getMedrecno());
        Alergy1JText.setText(product.getA1());
        Alergy2JText.setText(product.getA2());
        Alergy3JText.setText(product.getA3());
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
