/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.MainProduct;

/**
 *
 * @author 16177
 */
public class PrintResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrintResultJPanel
     */
    MainProduct product;
    
    public PrintResultJPanel(MainProduct product) {
        initComponents();
        this.product = product;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleJLabel = new javax.swing.JLabel();
        WeightJLable = new javax.swing.JLabel();
        SSNJLable = new javax.swing.JLabel();
        FirstNameJText = new javax.swing.JTextField();
        LastNameJText = new javax.swing.JTextField();
        PhoneNumberJText = new javax.swing.JTextField();
        FirstNameJLable = new javax.swing.JLabel();
        DOBJText = new javax.swing.JTextField();
        LastNameJLable = new javax.swing.JLabel();
        AgeJText = new javax.swing.JTextField();
        PhoneNumberJLable = new javax.swing.JLabel();
        HeightJText = new javax.swing.JTextField();
        DOBJLable = new javax.swing.JLabel();
        WeightJText = new javax.swing.JTextField();
        AgeJLable = new javax.swing.JLabel();
        SSNJText = new javax.swing.JTextField();
        HeightJLable = new javax.swing.JLabel();
        StateJLable = new javax.swing.JLabel();
        ZipCodeJLable = new javax.swing.JLabel();
        StreetAddJText = new javax.swing.JTextField();
        CityJText = new javax.swing.JTextField();
        StateJText = new javax.swing.JTextField();
        StreetAddJLable = new javax.swing.JLabel();
        ZipCodeJText = new javax.swing.JTextField();
        CityJLable = new javax.swing.JLabel();
        BankNameJLable = new javax.swing.JLabel();
        AccBalanceJText = new javax.swing.JTextField();
        BankRoutingNumberJLable = new javax.swing.JLabel();
        BankAccNumberJLable = new javax.swing.JLabel();
        AccBalanceJLable = new javax.swing.JLabel();
        BankNameJText = new javax.swing.JTextField();
        BankRoutingNumberJText = new javax.swing.JTextField();
        BankAccNumberJText = new javax.swing.JTextField();
        LicenseNumberJLable = new javax.swing.JLabel();
        BloodTypeJText = new javax.swing.JTextField();
        DOIJLable = new javax.swing.JLabel();
        DOEJLable = new javax.swing.JLabel();
        BloodTypeJLable = new javax.swing.JLabel();
        LicenseNumberJText = new javax.swing.JTextField();
        DOIJText = new javax.swing.JTextField();
        DOEJText = new javax.swing.JTextField();
        MedicalRecNumberJText = new javax.swing.JTextField();
        MedicalRecNumberJLable = new javax.swing.JLabel();
        Alergy1JText = new javax.swing.JTextField();
        Alergy2JText = new javax.swing.JTextField();
        Alergy3JText = new javax.swing.JTextField();
        Allergy1JLable = new javax.swing.JLabel();
        Alergy2JLable = new javax.swing.JLabel();
        Alergy3JLable = new javax.swing.JLabel();
        AdrsJLable = new javax.swing.JLabel();
        CheckingJLable1 = new javax.swing.JLabel();
        BankNameJLable1 = new javax.swing.JLabel();
        BankRoutingNumberJLable1 = new javax.swing.JLabel();
        CBankNameJText1 = new javax.swing.JTextField();
        CBankRoutingNumberJText1 = new javax.swing.JTextField();
        CAccBalanceJText1 = new javax.swing.JTextField();
        BankAccNumberJLable1 = new javax.swing.JLabel();
        AccBalanceJLable1 = new javax.swing.JLabel();
        CBankAccNumberJText1 = new javax.swing.JTextField();
        SavingJLable = new javax.swing.JLabel();
        DmeoJLable = new javax.swing.JLabel();
        LicenseJLable = new javax.swing.JLabel();
        MedicalJLable = new javax.swing.JLabel();
        MedicalRecNumberJLable1 = new javax.swing.JLabel();
        PhotoLabel = new javax.swing.JLabel();
        AccBalanceJLable2 = new javax.swing.JLabel();
        AccBalanceJLable3 = new javax.swing.JLabel();
        AccTypeJText = new javax.swing.JTextField();
        CAccTypeJText1 = new javax.swing.JTextField();

        TitleJLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        TitleJLabel.setForeground(new java.awt.Color(153, 0, 0));
        TitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleJLabel.setText("Final Personal Information Report");
        TitleJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        WeightJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        WeightJLable.setText("Weight:");

        SSNJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        SSNJLable.setText("SSN:");

        FirstNameJText.setEditable(false);

        LastNameJText.setEditable(false);

        PhoneNumberJText.setEditable(false);

        FirstNameJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        FirstNameJLable.setText("First Name:");

        DOBJText.setEditable(false);

        LastNameJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        LastNameJLable.setText("Last Name:");

        AgeJText.setEditable(false);

        PhoneNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        PhoneNumberJLable.setText("Phone Number:");

        HeightJText.setEditable(false);
        HeightJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightJTextActionPerformed(evt);
            }
        });

        DOBJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOBJLable.setText("Date of Birth:");

        WeightJText.setEditable(false);

        AgeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AgeJLable.setText("Age:");

        SSNJText.setEditable(false);

        HeightJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        HeightJLable.setText("Height:");

        StateJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        StateJLable.setText("State:");

        ZipCodeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        ZipCodeJLable.setText("Zip Code:");

        StreetAddJText.setEditable(false);

        CityJText.setEditable(false);

        StateJText.setEditable(false);

        StreetAddJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        StreetAddJLable.setText("Street Address:");

        ZipCodeJText.setEditable(false);
        ZipCodeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeJTextActionPerformed(evt);
            }
        });

        CityJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        CityJLable.setText("City:");

        BankNameJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankNameJLable.setText("Bank Name:");

        AccBalanceJText.setEditable(false);

        BankRoutingNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankRoutingNumberJLable.setText("Routing Number:");

        BankAccNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankAccNumberJLable.setText(" Account Number:");

        AccBalanceJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AccBalanceJLable.setText("Account Balance:");

        BankNameJText.setEditable(false);

        BankRoutingNumberJText.setEditable(false);

        BankAccNumberJText.setEditable(false);

        LicenseNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        LicenseNumberJLable.setText("License Number:");

        BloodTypeJText.setEditable(false);

        DOIJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOIJLable.setText("Date of Issue:");

        DOEJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOEJLable.setText("Date of Expiry:");

        BloodTypeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BloodTypeJLable.setText("Blood type:");

        LicenseNumberJText.setEditable(false);

        DOIJText.setEditable(false);

        DOEJText.setEditable(false);

        MedicalRecNumberJText.setEditable(false);

        MedicalRecNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MedicalRecNumberJLable.setText("Medical Record Number:");

        Alergy1JText.setEditable(false);

        Alergy2JText.setEditable(false);

        Alergy3JText.setEditable(false);

        Allergy1JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Allergy1JLable.setText("Alergy 1:");

        Alergy2JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Alergy2JLable.setText("Alergy 2:");

        Alergy3JLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Alergy3JLable.setText("Alergy 3:");

        AdrsJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AdrsJLable.setForeground(new java.awt.Color(0, 153, 51));
        AdrsJLable.setText("Address Information-");

        CheckingJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        CheckingJLable1.setForeground(new java.awt.Color(0, 153, 51));
        CheckingJLable1.setText("Checking Account Information-");

        BankNameJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankNameJLable1.setText("Bank Name:");

        BankRoutingNumberJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankRoutingNumberJLable1.setText("Routing Number:");

        CBankNameJText1.setEditable(false);

        CBankRoutingNumberJText1.setEditable(false);

        CAccBalanceJText1.setEditable(false);

        BankAccNumberJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BankAccNumberJLable1.setText("Account Number:");

        AccBalanceJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AccBalanceJLable1.setText("Account Balance:");

        CBankAccNumberJText1.setEditable(false);

        SavingJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        SavingJLable.setForeground(new java.awt.Color(0, 153, 51));
        SavingJLable.setText("Saving Account Information-");

        DmeoJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DmeoJLable.setForeground(new java.awt.Color(0, 153, 51));
        DmeoJLable.setText("Demographic Information-");

        LicenseJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        LicenseJLable.setForeground(new java.awt.Color(0, 153, 51));
        LicenseJLable.setText("License Information-");

        MedicalJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MedicalJLable.setForeground(new java.awt.Color(0, 153, 51));
        MedicalJLable.setText("Medical Iformation-");

        MedicalRecNumberJLable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MedicalRecNumberJLable1.setText("License Photo:");

        PhotoLabel.setFont(new java.awt.Font("Aldhabi", 2, 24)); // NOI18N

        AccBalanceJLable2.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AccBalanceJLable2.setText("Type:");

        AccBalanceJLable3.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        AccBalanceJLable3.setText("Type:");

        AccTypeJText.setEditable(false);

        CAccTypeJText1.setEditable(false);
        CAccTypeJText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAccTypeJText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavingJLable)
                            .addComponent(CheckingJLable1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(FirstNameJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FirstNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LastNameJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PhoneNumberJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PhoneNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DOBJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DOBJText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AgeJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HeightJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(WeightJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SSNJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SSNJText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AdrsJLable)
                                    .addComponent(DmeoJLable)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(StreetAddJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StreetAddJText, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CityJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CityJText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StateJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StateJText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ZipCodeJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ZipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankNameJLable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankNameJLable1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CBankNameJText1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankRoutingNumberJLable1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CBankRoutingNumberJText1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankRoutingNumberJLable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BankRoutingNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankAccNumberJLable1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CBankAccNumberJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BankAccNumberJLable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BankAccNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AccBalanceJLable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AccBalanceJText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AccBalanceJLable1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CAccBalanceJText1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AccBalanceJLable3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CAccTypeJText1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AccBalanceJLable2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AccTypeJText, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))))
                                .addGap(99, 99, 99)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicalJLable)
                            .addComponent(LicenseJLable)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MedicalRecNumberJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MedicalRecNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Allergy1JLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Alergy1JText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Alergy2JLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Alergy2JText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Alergy3JLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Alergy3JText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LicenseNumberJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LicenseNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DOIJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DOIJText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DOEJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DOEJText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BloodTypeJLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BloodTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MedicalRecNumberJLable1)
                                        .addGap(18, 18, 18)
                                        .addComponent(PhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DmeoJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeJLable)
                    .addComponent(AgeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightJLable)
                    .addComponent(HeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeightJLable)
                    .addComponent(WeightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumberJLable)
                    .addComponent(PhoneNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBJLable)
                    .addComponent(FirstNameJLable)
                    .addComponent(FirstNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameJLable)
                    .addComponent(LastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNJLable)
                    .addComponent(SSNJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(AdrsJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StreetAddJLable)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StateJLable)
                        .addComponent(StateJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ZipCodeJLable)
                        .addComponent(ZipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StreetAddJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CityJLable)
                        .addComponent(CityJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(SavingJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNameJLable)
                    .addComponent(BankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankRoutingNumberJLable)
                    .addComponent(BankRoutingNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankAccNumberJLable)
                    .addComponent(BankAccNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccBalanceJLable)
                    .addComponent(AccBalanceJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccBalanceJLable2)
                    .addComponent(AccTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(CheckingJLable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNameJLable1)
                    .addComponent(CBankNameJText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankRoutingNumberJLable1)
                    .addComponent(CBankRoutingNumberJText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankAccNumberJLable1)
                    .addComponent(CBankAccNumberJText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccBalanceJLable1)
                    .addComponent(CAccBalanceJText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccBalanceJLable3)
                    .addComponent(CAccTypeJText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(LicenseJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNumberJLable)
                    .addComponent(LicenseNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOIJLable)
                    .addComponent(DOIJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOEJLable)
                    .addComponent(DOEJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodTypeJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicalRecNumberJLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(MedicalJLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalRecNumberJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicalRecNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Allergy1JLable)
                    .addComponent(Alergy1JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy2JLable)
                    .addComponent(Alergy2JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy3JLable)
                    .addComponent(Alergy3JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HeightJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightJTextActionPerformed

    private void ZipCodeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeJTextActionPerformed

    private void CAccTypeJText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAccTypeJText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAccTypeJText1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccBalanceJLable;
    private javax.swing.JLabel AccBalanceJLable1;
    private javax.swing.JLabel AccBalanceJLable2;
    private javax.swing.JLabel AccBalanceJLable3;
    private javax.swing.JTextField AccBalanceJText;
    private javax.swing.JTextField AccTypeJText;
    private javax.swing.JLabel AdrsJLable;
    private javax.swing.JLabel AgeJLable;
    private javax.swing.JTextField AgeJText;
    private javax.swing.JTextField Alergy1JText;
    private javax.swing.JLabel Alergy2JLable;
    private javax.swing.JTextField Alergy2JText;
    private javax.swing.JLabel Alergy3JLable;
    private javax.swing.JTextField Alergy3JText;
    private javax.swing.JLabel Allergy1JLable;
    private javax.swing.JLabel BankAccNumberJLable;
    private javax.swing.JLabel BankAccNumberJLable1;
    private javax.swing.JTextField BankAccNumberJText;
    private javax.swing.JLabel BankNameJLable;
    private javax.swing.JLabel BankNameJLable1;
    private javax.swing.JTextField BankNameJText;
    private javax.swing.JLabel BankRoutingNumberJLable;
    private javax.swing.JLabel BankRoutingNumberJLable1;
    private javax.swing.JTextField BankRoutingNumberJText;
    private javax.swing.JLabel BloodTypeJLable;
    private javax.swing.JTextField BloodTypeJText;
    private javax.swing.JTextField CAccBalanceJText1;
    private javax.swing.JTextField CAccTypeJText1;
    private javax.swing.JTextField CBankAccNumberJText1;
    private javax.swing.JTextField CBankNameJText1;
    private javax.swing.JTextField CBankRoutingNumberJText1;
    private javax.swing.JLabel CheckingJLable1;
    private javax.swing.JLabel CityJLable;
    private javax.swing.JTextField CityJText;
    private javax.swing.JLabel DOBJLable;
    private javax.swing.JTextField DOBJText;
    private javax.swing.JLabel DOEJLable;
    private javax.swing.JTextField DOEJText;
    private javax.swing.JLabel DOIJLable;
    private javax.swing.JTextField DOIJText;
    private javax.swing.JLabel DmeoJLable;
    private javax.swing.JLabel FirstNameJLable;
    private javax.swing.JTextField FirstNameJText;
    private javax.swing.JLabel HeightJLable;
    private javax.swing.JTextField HeightJText;
    private javax.swing.JLabel LastNameJLable;
    private javax.swing.JTextField LastNameJText;
    private javax.swing.JLabel LicenseJLable;
    private javax.swing.JLabel LicenseNumberJLable;
    private javax.swing.JTextField LicenseNumberJText;
    private javax.swing.JLabel MedicalJLable;
    private javax.swing.JLabel MedicalRecNumberJLable;
    private javax.swing.JLabel MedicalRecNumberJLable1;
    private javax.swing.JTextField MedicalRecNumberJText;
    private javax.swing.JLabel PhoneNumberJLable;
    private javax.swing.JTextField PhoneNumberJText;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JLabel SSNJLable;
    private javax.swing.JTextField SSNJText;
    private javax.swing.JLabel SavingJLable;
    private javax.swing.JLabel StateJLable;
    private javax.swing.JTextField StateJText;
    private javax.swing.JLabel StreetAddJLable;
    private javax.swing.JTextField StreetAddJText;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.JLabel WeightJLable;
    private javax.swing.JTextField WeightJText;
    private javax.swing.JLabel ZipCodeJLable;
    private javax.swing.JTextField ZipCodeJText;
    // End of variables declaration//GEN-END:variables

    private void display() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        FirstNameJText.setText(product.getFirstname());
        LastNameJText.setText(product.getLastname());
        PhoneNumberJText.setText(product.getPhonenumber());
        DOBJText.setText(product.getDob());
        AgeJText.setText(product.getAge());
        HeightJText.setText(product.getHeight());
        WeightJText.setText(product.getWeight());
        SSNJText.setText(product.getSsn());
        StreetAddJText.setText(product.getStreetAdrs());
        CityJText.setText(product.getCity());
        StateJText.setText(product.getState());
        ZipCodeJText.setText(product.getZipcode());
        BankNameJText.setText(product.getBankname());
        BankRoutingNumberJText.setText(product.getBankroutingno());
        BankAccNumberJText.setText(product.getBankaccno());
        AccBalanceJText.setText(product.getAccbal());
        AccTypeJText.setText(product.getAcctype());
        CBankNameJText1.setText(product.getcBankname());
        CBankRoutingNumberJText1.setText(product.getCbankroutingno());
        CBankAccNumberJText1.setText(product.getCbankaccno());
        CAccBalanceJText1.setText(product.getCaccbal());
        CAccTypeJText1.setText(product.getCacctype());
        LicenseNumberJText.setText(product.getLicenseno());
        DOIJText.setText(product.getDoi());
        DOEJText.setText(product.getDoe());
        BloodTypeJText.setText(product.getBloodtype());
        MedicalRecNumberJText.setText(product.getMedrecno());
        Alergy1JText.setText(product.getA1());
        Alergy2JText.setText(product.getA2());
        Alergy3JText.setText(product.getA3());
        PhotoLabel.setIcon(product.imageIcon);    }
}
