/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.MainProduct;

/**
 *
 * @author 16177
 */
public class ViewLicenseInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewKicenseInfoJPanel
     */
    MainProduct product;
    public ViewLicenseInfoJPanel(MainProduct product) {
        initComponents();
        this.product=product;
        LicenseNumberJText.setEnabled(false);
        DOIJText.setEnabled(false);
        DOEJText.setEnabled(false);
        BloodTypeJText.setEnabled(false);
          display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BloodTypeJText = new javax.swing.JTextField();
        DOIJLable = new javax.swing.JLabel();
        DOEJLable = new javax.swing.JLabel();
        BloodTypeJLable = new javax.swing.JLabel();
        LicenseNumberJText = new javax.swing.JTextField();
        DOIJText = new javax.swing.JTextField();
        Photolabel = new javax.swing.JLabel();
        TitleJLabel = new javax.swing.JLabel();
        Piclabel = new javax.swing.JLabel();
        DOEJText = new javax.swing.JTextField();
        LicenseNumberJLable = new javax.swing.JLabel();

        DOIJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOIJLable.setText("Date of Issue:");

        DOEJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DOEJLable.setText("Date of Expiry:");

        BloodTypeJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        BloodTypeJLable.setText("Blood type:");

        TitleJLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        TitleJLabel.setForeground(new java.awt.Color(153, 0, 0));
        TitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleJLabel.setText("Driver's License Information");
        TitleJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        Piclabel.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        Piclabel.setText("Picture:");

        LicenseNumberJLable.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        LicenseNumberJLable.setText("License Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DOEJLable)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DOIJLable, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LicenseNumberJLable))
                    .addComponent(BloodTypeJLable)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Piclabel)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LicenseNumberJText, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(DOIJText, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(BloodTypeJText, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(DOEJText, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(Photolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNumberJLable)
                    .addComponent(LicenseNumberJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOIJLable)
                    .addComponent(DOIJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOEJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOEJLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodTypeJLable)
                    .addComponent(BloodTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Piclabel)
                    .addComponent(Photolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodTypeJLable;
    private javax.swing.JTextField BloodTypeJText;
    private javax.swing.JLabel DOEJLable;
    private javax.swing.JTextField DOEJText;
    private javax.swing.JLabel DOIJLable;
    private javax.swing.JTextField DOIJText;
    private javax.swing.JLabel LicenseNumberJLable;
    private javax.swing.JTextField LicenseNumberJText;
    private javax.swing.JLabel Photolabel;
    private javax.swing.JLabel Piclabel;
    private javax.swing.JLabel TitleJLabel;
    // End of variables declaration//GEN-END:variables

    private void display() {
         LicenseNumberJText.setText(product.getLicenseno());
        DOIJText.setText(product.getDoi());
        DOEJText.setText(product.getDoe());
        BloodTypeJText.setText(product.getBloodtype());
        Photolabel.setIcon(product.imageIcon);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
